FROM yohanchatelain/verificarlo:pytorch-prism-ud as fuzzy

FROM deepmi/fastsurfer:cpu-v2.1.1

#RUN /bin/bash -c "mkdir -p /workspace"

COPY --from=fuzzy /opt/conda/lib/python3.8/site-packages/torch/ /venv/lib/python3.8/site-packages/torch
COPY --from=fuzzy /usr/local/lib/* /usr/local/lib/.
COPY --from=fuzzy /usr/lib/llvm-7/lib/libgomp.so /usr/lib/llvm-7/lib/libgomp.so
COPY --from=fuzzy /usr/lib/llvm-7/lib/libiomp5.so /usr/lib/llvm-7/lib/libiomp5.so
COPY --from=fuzzy /usr/lib/llvm-7/lib/libomp.so /usr/lib/llvm-7/lib/libomp.so
COPY --from=fuzzy /usr/lib/llvm-7/lib/libclang.so.1 /usr/lib/llvm-7/lib/libclang.so.1
COPY --from=fuzzy /usr/lib/llvm-7/lib/libomp-7.so.5 /usr/lib/llvm-7/lib/libomp-7.so.5
COPY --from=fuzzy /usr/lib/llvm-7/lib/libomp.so.5 /usr/lib/llvm-7/lib/libomp.so.5
COPY --from=fuzzy /usr/lib/x86_64-linux-gnu/* /usr/lib/x86_64-linux-gnu/.
#COPY --from=fuzzy /usr/lib/x86_64-linux-gnu/libstdc++.so.6* /usr/lib/x86_64-linux-gnu/.

RUN pip install pandas==1.3 --no-deps

ENTRYPOINT ["/bin/bash"]

