FROM ubuntu:22.04

RUN apt-get update && \
  apt-get install -y --no-install-recommends build-essential git wget curl bc \
  automake libtool parallel \
  clang-15 libclang-15-dev llvm-15 llvm-15-dev llvm-15-tools \
  libomp-15-dev libomp5-15 \
  libgmp-dev libgmpxx4ldbl libmpfr-dev libmpfr6 \
  python3-pip && \
  wget --no-check-certificate https://github.com/bazelbuild/bazelisk/releases/download/v1.26.0/bazelisk-amd64.deb && \
  apt install -y  ./bazelisk-amd64.deb && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 100 && \
  update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 100 && \
  update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-15 100 

WORKDIR /build

COPY tools/install.sh /build/tools/install.sh
COPY tools/stochastic-rounding-evaluation /build/tools/stochastic-rounding-evaluation

RUN chmod +x /build/tools/install.sh && \
  cd /build/tools && \
  /build/tools/install.sh