FROM yohanchatelain/verificarlo:pytorch-prism-ud

#RUN pip install torchvision==0.17 --no-deps

# Set environment variables for Conda
ENV PATH=/opt/conda/bin:$PATH
ENV CONDA_DEFAULT_ENV=base

SHELL ["/bin/bash", "-c"]
RUN source activate base && conda info

# Install MNIST dependencies
RUN conda install -y pytorch::torchvision=0.16 --no-deps
RUN conda install -y Pillow=10.4.0 --no-deps
RUN conda install -y jpeg=9e --no-deps 
RUN conda install -y openjpeg=2.5.2 --no-deps

ENTRYPOINT ["bash"]

